version: '3'
services:
  notebook:
    image: jupyter/base-notebook:latest
    labels:
      description: Jupyter Notebooks
      name: jupyter notebook 
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work/
    command: "start-notebook.sh --NotebookApp.token="
