version: '3'
services:
  database: 
    image: mysql
    ports:   
      - "3306:3306"
    volumes:
      - ./sql:/var/lib/mysql     
    environment:
        MYSQL_DATABASE: "test"
        MYSQL_USER: "test"
        MYSQL_PASSWORD: "test"
        MYSQL_ROOT_PASSWORD: "root"
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
     
  notebook:
    image: harry/jupyter-notebook 
    labels:
      name: jupyter notebook 
    ports:
      - "8888:8888"
    volumes:
      - ./work:/home/jovyan/work/
    command: "start-notebook.sh --NotebookApp.token="
    depends_on: 
    - database
